# Generated by Django 4.0.4 on 2022-06-11 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='access_token_paypal',
            name='client_id',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name='Token de Acceso Paypal'),
        ),
        migrations.AddField(
            model_name='access_token_paypal',
            name='secret_id',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name='Token de Acceso Paypal'),
        ),
        migrations.AlterField(
            model_name='access_token_paypal',
            name='access_token',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Token de Acceso Paypal'),
        ),
    ]
