# Generated by Django 4.0.4 on 2022-06-11 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_access_token_paypal_client_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='access_token_paypal',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='access_token_paypal',
            name='secret_id',
        ),
    ]
