# Generated by Django 4.0.4 on 2022-05-10 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='direccion_facturacion',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Direccion'),
        ),
    ]
