# Generated by Django 4.0.4 on 2022-05-23 18:31

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='foto',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='media/account/default.png', force_format=None, keep_meta=True, null=True, quality=0, size=[500, 500], upload_to='account'),
        ),
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
