# Generated by Django 4.0.4 on 2022-05-25 19:36

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='foto',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='media/account/default.png', force_format=None, keep_meta=True, null=True, quality=100, size=[500, 300], upload_to='account'),
        ),
    ]
