# Generated by Django 4.0.4 on 2022-05-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_biografia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='biografia',
            field=models.CharField(blank=True, max_length=150, verbose_name='Bio'),
        ),
    ]
