# Generated by Django 4.0.4 on 2022-05-26 02:27

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_user_biografia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='biografia',
            field=models.CharField(blank=True, max_length=60, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='user',
            name='foto',
            field=django_resized.forms.ResizedImageField(crop=None, default='media/account/default.png', force_format=None, keep_meta=True, null=True, quality=100, size=[500, 300], upload_to='account'),
        ),
    ]
