# Generated by Django 4.0.4 on 2022-05-26 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_user_biografia_alter_user_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='foto',
            field=models.ImageField(blank=True, default='media/account/default.png', null=True, upload_to='account'),
        ),
    ]
