# Generated by Django 4.0.4 on 2022-05-26 02:45

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_user_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='foto',
            field=sorl.thumbnail.fields.ImageField(blank=True, default='media/account/default.png', null=True, upload_to='account'),
        ),
    ]
