# Generated by Django 4.0.4 on 2022-06-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_user_biografia'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='apodo',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
