# Generated by Django 4.0.4 on 2022-06-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_user_apodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='apodo',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
    ]
