# Generated by Django 4.0.4 on 2022-06-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_user_verificado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tipo_celebridad',
            field=models.ManyToManyField(blank=True, null=True, to='users.tipocelebridad'),
        ),
    ]
