# Generated by Django 4.0.4 on 2022-06-21 17:59

from django.db import migrations, models
import django_resized.forms
import users.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_alter_user_tipo_celebridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='banner',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, quality=75, size=[1200, 300], upload_to=users.utils.banner_directory_path_profile),
        ),
        migrations.AlterField(
            model_name='user',
            name='tipo_celebridad',
            field=models.ManyToManyField(blank=True, to='users.tipocelebridad'),
        ),
    ]
