# Generated by Django 4.0.4 on 2022-10-05 22:06

from django.db import migrations
import django_resized.forms
import users.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_user_banner_alter_user_tipo_celebridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='banner',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, quality=85, size=[1280, 720], upload_to=users.utils.banner_directory_path_profile),
        ),
    ]
