# Generated by Django 4.0.9 on 2023-02-07 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_seguidorusuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SeguidorUsuario',
        ),
    ]
