# Generated by Django 4.0.4 on 2022-05-31 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacion',
            old_name='usuario',
            new_name='user',
        ),
    ]
