# Generated by Django 4.0.4 on 2022-06-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_alter_publicacion_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha Actualizacion'),
        ),
    ]
