# Generated by Django 4.0.4 on 2022-06-10 16:21

from django.db import migrations, models
import social.utils


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_alter_publicacion_descripcion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicacion',
            options={'verbose_name_plural': 'Publicaciones'},
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to=social.utils.postDirectory, validators=[social.utils.valid_file_extention, social.utils.valid_file_size]),
        ),
    ]
