# Generated by Django 4.0.4 on 2022-06-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_alter_publicacion_options_alter_publicacion_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha Actualizacion'),
        ),
    ]
