# Generated by Django 4.0.4 on 2022-06-11 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_alter_publicacion_fecha_actualizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='nswf',
            field=models.BooleanField(default=False, verbose_name='nswf'),
        ),
    ]
