# Generated by Django 4.0.4 on 2022-06-11 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_publicacion_nswf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='nswf',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='nsfw',
            field=models.BooleanField(default=False, verbose_name='nsfw'),
        ),
    ]
