# Generated by Django 4.0.4 on 2022-06-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_remove_publicacion_nswf_publicacion_nsfw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='nsfw',
            field=models.BooleanField(default=False, verbose_name='NSFW'),
        ),
    ]
