# Generated by Django 4.0.4 on 2022-10-05 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0012_alter_publicacion_nsfw'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liked_Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.publicacion', verbose_name='Likes')),
                ('id_usuario', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Likes de Usuarios')),
            ],
        ),
    ]
