# Generated by Django 4.0.4 on 2022-10-08 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0014_likedpublicacion_delete_liked_publicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedpublicacion',
            name='id_publicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.publicacion', verbose_name='Publicacion'),
        ),
        migrations.AlterField(
            model_name='likedpublicacion',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(max_length=120, verbose_name='Comentario')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Like')),
                ('id_autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('id_publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.publicacion', verbose_name='Publicacion')),
            ],
        ),
    ]
