# Generated by Django 4.0.4 on 2022-10-08 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0016_likecomentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likecomentarios',
            name='id_comentario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.comentarios', verbose_name='Comentarios'),
        ),
    ]
