# Generated by Django 4.0.4 on 2022-10-09 22:11

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0017_alter_likecomentarios_id_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='descripcion',
            field=tinymce.models.HTMLField(blank=True, max_length=2200, null=True, verbose_name='Descripcion'),
        ),
    ]
