# Generated by Django 4.0.8 on 2022-10-20 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0019_alter_comentarios_comentario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentarios',
            old_name='id_autor',
            new_name='id_usuario',
        ),
    ]
