# Generated by Django 4.0.8 on 2022-10-20 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0020_rename_id_autor_comentarios_id_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentarios',
            old_name='id_usuario',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='likecomentarios',
            old_name='id_usuario',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='likedpublicacion',
            old_name='id_usuario',
            new_name='user',
        ),
    ]
