# Generated by Django 4.0.9 on 2023-02-07 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0022_seguidorusuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SeguidorUsuario',
        ),
    ]
