# Generated by Django 4.0.4 on 2022-06-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_remove_publicacion_titulo_alter_publicacion_archivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='descripcion',
            field=models.TextField(blank=True, max_length=280, verbose_name='Descripcion'),
        ),
    ]
