# Generated by Django 4.0.9 on 2023-02-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='closed_by_first_user',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='thread',
            name='closed_by_second_user',
            field=models.DateTimeField(),
        ),
    ]
